#!/usr/bin/python
# -*- coding: utf-8 -*-

from parameter import Parameter
from definitions import ParameterDefinitions as Prms


label = 'Booster'

parameter_list = [

  Parameter(
    name     = 'Booster injection beam energy',
    group    = 'LNLS',
    value    = Prms.bo_injection_beam_energy,
    symbol   = r'<math>E_\text{inj}</math>',
    units    = 'GeV',
    revision = '2014-08-04',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster injection beam gamma factor',
    group    = 'FAC',
    value    = Prms.bo_injection_beam_gamma_factor,
    symbol   = r'<math>\gamma_\text{inj}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster injection beam energy'],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster injection beam beta factor',
    group    = 'FAC',
    value    = Prms.bo_injection_beam_beta_factor,
    symbol   = r'<math>\beta_\text{inj}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster injection beam gamma factor'],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster injection beam velocity',
    group    = 'FAC',
    value    = Prms.bo_injection_beam_velocity,
    symbol   = r'<math>v_\text{inj}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster injection beam beta factor'],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster extraction beam energy',
    group    = 'LNLS',
    value    = Prms.bo_extraction_beam_energy,
    symbol   = r'<math>E_\text{ext}</math>',
    units    = 'GeV',
    revision = '2014-08-04',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster extraction beam gamma factor',
    group    = 'FAC',
    value    = Prms.bo_extraction_beam_gamma_factor,
    symbol   = r'<math>\gamma_\text{ext}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam energy'],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster extraction beam beta factor',
    group    = 'FAC',
    value    = Prms.bo_extraction_beam_beta_factor,
    symbol   = r'<math>\beta_\text{ext}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam gamma factor'],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster extraction beam velocity',
    group    = 'FAC',
    value    = Prms.bo_extraction_beam_velocity,
    symbol   = r'<math>v_\text{ext}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam beta factor'],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster circumference',
    group    = 'LNLS',
    value    = Prms.bo_circumference,
    symbol   = r'<math>C</math>',
    units    = 'm',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),
  
  Parameter(
    name     = 'Booster lattice symmetry',
    group    = 'FAC',
    value    = Prms.bo_lattice_symmetry,
    symbol   = r'<math>N_\text{SUPERCELLS}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster beam current',
    group    = 'FAC',
    value    = Prms.bo_beam_current,
    symbol   = r'<math>I</math>',
    units    = 'mA',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster extraction revolution period',
    group    = 'FAC',
    value    = Prms.bo_extraction_revolution_period,
    symbol   = r'<math>T_\text{rev}</math>',
    units    = unicode('μs',encoding='utf-8'),
    revision = '2014-08-01',
    deps     = ['Booster circumference',
                'Booster extraction beam velocity'],
    obs      = [],
  ),
 
  Parameter(
    name     = 'Booster extraction revolution frequency',
    group    = 'FAC',
    value    = Prms.bo_extraction_revolution_frequency,
    symbol   = r'<math>f_\text{rev}</math>',
    units    = u'MHz',
    revision = '2014-08-01',
    deps     = ['Booster extraction revolution period'],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster cycling frequency',
    group    = 'FAC',
    value    = Prms.bo_cycling_frequency,
    symbol   = r'<math>f_\text{cycle}</math>',
    units    = 'Hz',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster horizontal betatron tune',
    group    = 'FAC',
    value    = Prms.bo_horizontal_betatron_tune,
    symbol   = r'<math>\nu_x</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster lattice version',
                'Booster optics mode'],
    obs      = [],
  ),
                
  Parameter(
    name     = 'Booster vertical betatron tune',
    group    = 'FAC',
    value    = Prms.bo_vertical_betatron_tune,
    symbol   = r'<math>\nu_y</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster lattice version',
                'Booster optics mode'],
    obs      = [],
  ),
                  
  Parameter(
    name     = 'Booster synchrotron tune',
    group    = 'FAC',
    value    = Prms.bo_synchrotron_tune,
    symbol   = r'<math>\nu_s</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster lattice version',
                'Booster optics mode'],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster lattice version',
    group    = 'FAC',
    value    = Prms.bo_lattice_version,
    symbol   = '',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster optics mode',
    group    = 'FAC',
    value    = Prms.bo_optics_mode,
    symbol   = '',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster harmonic number',
    group    = 'FAC',
    value    = Prms.bo_harmonic_number,
    symbol   = r'<math>h</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = [unicode('<section begin=factors/>2<sup>2</sup>×2<sup>3</sup>×23<section end=factors/>',encoding='utf-8')],
  ),

  Parameter(
    name     = 'Booster extraction radiation integral I1',
    group    = 'FAC',
    value    = Prms.bo_extraction_radiation_integral_I1,
    symbol   = r'<math>I_\text{1}</math>',
    units    = 'm',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam magnetic rigidity',
                'Booster lattice version','Booster optics mode'],
    obs      = [r'<math>I_\text{1} = \oint{\frac{\eta_x}{\rho_x}\,ds}</math>'],
  ),

  Parameter(
    name     = 'Booster extraction radiation integral I2',
    group    = 'FAC',
    value    = Prms.bo_extraction_radiation_integral_I2,
    symbol   = r'<math>I_\text{2}</math>',
    units    = '1/m',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam magnetic rigidity',
                'Booster lattice version'],
    obs      = [r'<math>I_\text{2} = \oint{\frac{1}{\rho_x^2}\,ds}</math>'],
  ),
   
  Parameter(
    name     = 'Booster extraction radiation integral I3',
    group    = 'FAC',
    value    = Prms.bo_extraction_radiation_integral_I3,
    symbol   = r'<math>I_\text{3}</math>',
    units    = '1/m^2',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam magnetic rigidity',
                'Booster lattice version'],
    obs      = [r'<math>I_\text{3} = \oint{\frac{1}{|\rho_x|^3}\,ds}</math>'],
  ),
                  
  Parameter(
    name     = 'Booster extraction radiation integral I4',
    group    = 'FAC',
    value    = Prms.bo_extraction_radiation_integral_I4,
    symbol   = r'<math>I_\text{4}</math>',
    units    = '1/m',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam magnetic rigidity',
                'Booster lattice version'],
    obs      = [r'<math>I_\text{4} = \frac{\eta_x(s_0) \tan \theta(s_0)}{\rho_x^2} + \oint{\frac{\eta_x}{\rho_x^3} \left(1 + 2 \rho_x^2 k\right)\,ds} + \frac{\eta_x(s_1) \tan \theta(s_1)}{\rho_x^2}</math>'],
  ),
                  
  Parameter(
    name     = 'Booster extraction radiation integral I5',
    group    = 'FAC',
    value    = Prms.bo_extraction_radiation_integral_I5,
    symbol   = r'<math>I_\text{5}</math>',
    units    = '1/m',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam magnetic rigidity',
                'Booster lattice version',
                'Booster optics mode'],
    obs      = [r'<math>I_\text{5} = \oint{\frac{H_x}{|\rho_x|^3}\,ds}</math>',
                r"<math>H_x \equiv \gamma_x \eta_x^2 + 2 \alpha_x \eta_x \eta_x^' + \beta_x {\eta_x^'}^2</math>"],
  ),
                  
  Parameter(
    name     = 'Booster extraction radiation integral I6',
    group    = 'FAC',
    value    = Prms.bo_extraction_radiation_integral_I6,
    symbol   = r'<math>I_\text{6}</math>',
    units    = '1/m',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam magnetic rigidity',
                'Booster lattice version',
                'Booster optics mode'],
    obs      = [r'<math>I_\text{6} = \oint{k^2 \eta_x^2\,ds}</math>'],
  ),

  Parameter(
    name     = 'Booster extraction linear momentum compaction',
    group    = 'FAC',
    value    = Prms.bo_extraction_linear_momentum_compaction,
    symbol   = r'<math>\alpha_\text{1}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster extraction radiation integral I1',
                'Booster circumference'],
    obs      = [r'<math>\alpha_\text{1} = \frac{I_\text{1}}{C}</math>'],
  ),
 
  Parameter(
    name     = 'Booster extraction beam magnetic rigidity',
    group    = 'FAC',
    value    = Prms.bo_extraction_beam_magnetic_rigidity,
    symbol   = r'<math>(B\rho)</math>',
    units    = 'T.m',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam energy'],
    obs      = [r'<math>(B\rho) = \frac{p}{ec} = \frac{E}{ec^2}</math>'],
  ),

  Parameter(
    name     = 'Booster horizontal natural chromaticity',
    group    = 'FAC',
    value    = Prms.bo_horizontal_natural_chromaticity,
    symbol   = r'<math>\xi_{x0}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster lattice version',
                'Booster optics mode'],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster vertical natural chromaticity',
    group    = 'FAC',
    value    = Prms.bo_vertical_natural_chromaticity,
    symbol   = r'<math>\xi_{y0}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster lattice version',
                'Booster optics mode'],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster extraction horizontal damping partition number',
    group    = 'FAC',
    value    = Prms.bo_extraction_horizontal_damping_partition_number,
    symbol   = r'<math>J_x</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster extraction radiation integral I2',
                'Booster extraction radiation integral I4'],
    obs      = [r'<math>J_x = 1 - \frac{I_\text{4}}{I_\text{2}}</math>'],
  ),

  Parameter(
    name     = 'Booster extraction vertical damping partition number',
    group    = 'FAC',
    value    = Prms.bo_extraction_vertical_damping_partition_number,
    symbol   = r'<math>J_y</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = ['Vertical damping partition number is identically one for error-free machines for which vertical dispersion functions are zero everywhere.',
                r'<math>J_y = 1 - \frac{I_{4,y}}{I_\text{2}} \equiv 1</math>'],
  ),

  Parameter(
    name     = 'Booster extraction longitudinal damping partition number',
    group    = 'FAC',
    value    = Prms.bo_extraction_longitudinal_damping_partition_number,
    symbol   = r'<math>J_s</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster extraction horizontal damping partition number',
                'Booster extraction vertical damping partition number'],
    obs      = ["Its value is derived from Robinson's sum rule.",
                r'<math>J_s = 4 - J_x - J_y</math>'],
  ),
 
  Parameter(
    name     = 'Booster extraction natural emittance',
    group    = 'FAC',
    value    = Prms.bo_extraction_natural_emittance,
    symbol   = r'<math>\epsilon_0</math>',
    units    = unicode('nm⋅rad',encoding='utf-8'),
    revision = '2014-08-01',
    deps     = ['Booster extraction beam gamma factor',
                'Booster extraction horizontal damping partition number',
                'Booster extraction radiation integral I5',
                'Booster extraction radiation integral I2'],
    obs      = [r'<math>\epsilon_0 = C_\text{q} \frac{\gamma^2}{J_x} \frac{I_\text{5}}{I_\text{2}}</math>'],
  ),
  
  Parameter(
    name     = 'Booster extraction natural energy spread',
    group    = 'FAC',
    value    = Prms.bo_extraction_natural_energy_spread,
    symbol   = r'<math>\sigma_\delta</math>',
    units    = '%',
    revision = '2014-08-07',
    deps     = ['Booster extraction beam gamma factor',
                'Booster extraction radiation integral I2',
                'Booster extraction radiation integral I3',
                'Booster extraction radiation integral I4'],
    obs      = [r'<math>\sigma_\delta = \sqrt{C_\text{q} \gamma^2 \frac{I_\text{3}}{2 I_\text{2} + I_\text{4}}}</math>'],
  ),
  
  Parameter(
    name     = 'Booster extraction horizontal damping time',
    group    = 'FAC',
    value    = Prms.bo_extraction_horizontal_damping_time,
    symbol   = r'<math>\tau_x</math>',
    units    = 'ms',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam energy',
                'Booster extraction radiation integral I2',
                'Booster extraction horizontal damping partition number',
                'Booster circumference'],
    obs      = [r'<math>\tau_x = \frac{3(m_e c^2)^3}{r_e c} \frac{C}{E_0^3 I_2 J_x}</math>'],
  ),

  Parameter(
    name     = 'Booster extraction vertical damping time',
    group    = 'FAC',
    value    = Prms.bo_extraction_vertical_damping_time,
    symbol   = r'<math>\tau_y</math>',
    units    = 'ms',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam energy',
                'Booster extraction radiation integral I2',
                'Booster extraction vertical damping partition number',
                'Booster circumference'],
    obs      = [r'<math>\tau_y = \frac{3(m_e c^2)^3}{r_e c} \frac{C}{E_0^3 I_2 J_y}</math>'],
  ),

  Parameter(
    name     = 'Booster extraction longitudinal damping time',
    group    = 'FAC',
    value    = Prms.bo_extraction_longitudinal_damping_time,
    symbol   = r'<math>\tau_s</math>',
    units    = 'ms',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam energy',
                'Booster extraction radiation integral I2',
                'Booster extraction longitudinal damping partition number',
                'Booster circumference'],
    obs      = [r'<math>\tau_s = \frac{3(m_e c^2)^3}{r_e c} \frac{C}{E_0^3 I_2 J_s}</math>'],
  ),

  Parameter(
    name     = 'Booster number of dipoles',
    group    = 'FAC',
    value    = Prms.bo_number_of_dipoles,
    symbol   = r'<math>N_\text{DIP}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster hardedge length of dipoles',
    group    = 'FAC',
    value    = Prms.bo_hardedge_length_of_dipoles,
    symbol   = r'<math>L_\text{DIP}</math>',
    units    = 'm',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster injection dipole magnetic field',
    group    = 'FAC',
    value    = Prms.bo_injection_dipole_magnetic_field,
    symbol   = r'<math>B_\text{inj}</math>',
    units    = 'T',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),
  
  Parameter(
    name     = 'Booster extraction dipole magnetic field',
    group    = 'FAC',
    value    = Prms.bo_extraction_dipole_magnetic_field,
    symbol   = r'<math>B_\text{ext}</math>',
    units    = 'T',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster injection dipole bending radius',
    group    = 'FAC',
    value    = Prms.bo_injection_dipole_bending_radius,
    symbol   = r'<math>\rho_\text{inj}</math>',
    units    = 'm',
    revision = '2014-08-01',
    deps     = ['Booster injection beam magnetic rigidity',
                'Booster injection dipole magnetic field'],
    obs      = [r'<math>\rho_\text{inj} = \frac{ec/p}{B_\text{inj}} = \frac{(B\rho)}{B_\text{inj}}</math>'],
  ),

  Parameter(
    name     = 'Booster extraction dipole bending radius',
    group    = 'FAC',
    value    = Prms.bo_extraction_dipole_bending_radius,
    symbol   = r'<math>\rho_\text{ext}</math>',
    units    = 'm',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam magnetic rigidity',
                'Booster extraction dipole magnetic field'],
    obs      = [r'<math>\rho_\text{ext} = \frac{ec/p}{B_\text{ext}} = \frac{(B\rho)}{B_\text{ext}}</math>'],
  ),

  Parameter(
    name     = 'Booster injection beam magnetic rigidity',
    group    = 'FAC',
    value    = Prms.bo_injection_beam_magnetic_rigidity,
    symbol   = r'<math>(B\rho)</math>',
    units    = 'T.m',
    revision = '2014-08-01',
    deps     = ['Booster injection beam energy'],
    obs      = [r'<math>(B\rho) = \frac{p}{ec} = \frac{E}{ec^2}</math>'],
  ),

  Parameter(
    name     = 'Booster number of QF quadrupoles',
    group    = 'FAC',
    value    = Prms.bo_number_of_QF_quadrupoles,
    symbol   = r'<math>N_\text{QF}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster hardedge length of QF quadrupoles',
    group    = 'FAC',
    value    = Prms.bo_hardedge_length_of_QF_quadrupoles,
    symbol   = r'<math>L_\text{QF}</math>',
    units    = 'm',
    revision = '2014-08-01',
    deps     = '',
    obs      = [],
  ),

  Parameter(
    name     = 'Booster number of QD quadrupoles',
    group    = 'FAC',
    value    = Prms.bo_number_of_QD_quadrupoles,
    symbol   = r'<math>N_\text{QF}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster hardedge length of QD quadrupoles',
    group    = 'FAC',
    value    = Prms.bo_hardedge_length_of_QD_quadrupoles,
    symbol   = r'<math>L_\text{QF}</math>',
    units    = 'm',
    revision = '2014-08-01',
    deps     = '',
    obs      = [],
  ),

  Parameter(
    name     = 'Booster extraction RF frequency',
    group    = 'FAC',
    value    = Prms.bo_extraction_rf_frequency,
    symbol   = r'<math>f_\text{RF}</math>',
    units    = u'MHz',
    revision = '2014-08-01',
    deps     = ['Booster extraction revolution frequency',
                'Booster harmonic number'],
    obs      = [],
  ),
  
  Parameter(
    name     = 'Booster number of SF sextupoles',
    group    = 'FAC',
    value    = Prms.bo_number_of_SF_sextupoles,
    symbol   = r'<math>N_\text{SF}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster hardedge length of SF sextupoles',
    group    = 'FAC',
    value    = Prms.bo_hardedge_length_of_SF_sextupoles,
    symbol   = r'<math>L_\text{SF}</math>',
    units    = 'm',
    revision = '2014-08-01',
    deps     = '',
    obs      = [],
  ),

  Parameter(
    name     = 'Booster number of SD sextupoles',
    group    = 'FAC',
    value    = Prms.bo_number_of_SD_sextupoles,
    symbol   = r'<math>N_\text{SF}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = ['Bipolar.'],
  ),

  Parameter(
    name     = 'Booster hardedge length of SD sextupoles',
    group    = 'FAC',
    value    = Prms.bo_hardedge_length_of_SD_sextupoles,
    symbol   = r'<math>L_\text{SF}</math>',
    units    = 'm',
    revision = '2014-08-01',
    deps     = '',
    obs      = [],
  ),

  Parameter(
    name     = 'Booster extraction QF quadrupole maximum gradient',
    group    = 'FAC',
    value    = Prms.bo_extraction_QF_quadrupole_maximum_gradient,
    symbol   = r'<math>K_\text{QF,max}</math>',
    units    = 'T/m',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),
                
  Parameter(
    name     = 'Booster extraction QD quadrupole maximum absolute gradient',
    group    = 'FAC',
    value    = Prms.bo_extraction_QD_quadrupole_maximum_absolute_gradient,
    symbol   = r'<math>K_\text{QD,max}</math>',
    units    = 'T/m',
    revision = '2014-08-01',
    deps     = [],
    obs      = ['Bipolar.'],
  ),
                
  Parameter(
    name     = 'Booster injection QF quadrupole maximum gradient',
    group    = 'FAC',
    value    = Prms.bo_injection_QF_quadrupole_maximum_gradient,
    symbol   = r'<math>K_\text{QF,max}</math>',
    units    = 'T/m',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),
                
  Parameter(
    name     = 'Booster injection QD quadrupole maximum absolute gradient',
    group    = 'FAC',
    value    = Prms.bo_injection_QD_quadrupole_maximum_absolute_gradient,
    symbol   = r'<math>K_\text{QD,max}</math>',
    units    = 'T/m',
    revision = '2014-08-01',
    deps     = [],
    obs      = ['Bipolar.'],
  ),
                
  Parameter(
    name     = 'Booster maximum integrated sextupole',
    group    = 'FAC',
    value    = Prms.bo_maximum_integrated_sextupole,
    symbol   = r"<math>\left( \int \frac{B''}{2}\,\mathrm{d}s \right)_\text{max}</math>",
    units    = 'T/m',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),
                
  Parameter(
    name     = 'Booster extraction energy loss per turn',
    group    = 'FAC',
    value    = Prms.bo_extraction_energy_loss_per_turn,
    symbol   = r'<math>U_0</math>',
    units    = 'keV',
    revision = '2014-08-01',
    deps     = ['Booster extraction beam energy',
                'Booster extraction radiation integral I2'],
    obs      = [r'<math>U_0 = \oint{P_\gamma dt} = \frac{C_\gamma}{2\pi} E^4_0 I_2</math>'],
  ),
  
  Parameter(
    name     = 'Booster extraction radiation power',
    group    = 'FAC',
    value    = Prms.bo_extraction_radiation_power,
    symbol   = r'<math>P</math>',
    units    = 'kW',
    revision = '2014-08-01',
    deps     = ['Booster extraction energy loss per turn',
                'Booster beam current'],
    obs      = [r'<math>P = U_0 I</math>'],
  ),
  
  Parameter(
    name     = 'Booster RF cavity peak voltage',
    group    = 'FAC',
    value    = Prms.bo_rf_cavity_peak_voltage,
    symbol   = r'<math>V_\text{RF}</math>',
    units    = 'MV',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),
  
  Parameter(
    name     = 'Booster extraction RF wavelength',
    group    = 'FAC',
    value    = Prms.bo_extraction_rf_wavelength,
    symbol   = r'<math>\lambda_\text{RF}</math>',
    units    = u'm',
    revision = '2014-08-01',
    deps     = ['Booster extraction RF frequency'],
    obs      = [r'<math>\lambda_\text{RF} = \frac{c}{f_\text{RF}}</math>'],
  ),
  
  Parameter(
    name     = 'Booster extraction overvoltage',
    group    = 'FAC',
    value    = Prms.bo_extraction_overvoltage,
    symbol   = r'<math>q</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster RF cavity peak voltage',
                'Booster extraction energy loss per turn'],
    obs      = [r'<math>q = \frac{eV_\text{RF}}{U_0}</math>'],
  ),
  
  Parameter(
    name     = 'Booster extraction synchronous phase',
    group    = 'FAC',
    value    = Prms.bo_extraction_synchronous_phase,
    symbol   = r'<math>\phi_0</math>',
    units    = unicode('°',encoding='utf-8'),
    revision = '2014-08-01',
    deps     = ['Storage ring overvoltage'],
    obs      = [r'<math>\phi_0 = \pi - \arcsin\left(\frac{1}{q}\right)</math>'],
  ),

  Parameter(
    name     = 'Booster extraction synchrotron frequency',
    group    = 'FAC',
    value    = Prms.bo_extraction_synchrotron_frequency,
    symbol   = r'<math>f_s</math>',
    units    = 'kHz',
    revision = '2014-08-01',
    deps     = ['Booster extraction revolution frequency',
                'Booster synchrotron tune'],
    obs      = [r'<math>f_s = f_\text{rev} \left( \nu_s - \lfloor \nu_s\rfloor \right)</math>'],
  ),
 
  Parameter(
    name     = 'Booster extraction RF energy acceptance',
    group    = 'FAC',
    value    = Prms.bo_extraction_rf_energy_acceptance,
    symbol   = r'<math>\epsilon_\text{max}</math>',
    units    = '%',
    revision = '2014-08-01',
    deps     = ['Booster extraction overvoltage',
                'Booster extraction beam energy',
                'Booster extraction energy loss per turn',
                'Booster harmonic number',
                'Booster extraction linear momentum compaction'],
    obs      = [r'<math>\epsilon_\text{max} = \sqrt{\frac{1}{\pi h \alpha_x} \frac{U_0}{E} F(q)}</math>',
                r'<math>F(q) = 2 \left( \sqrt{q^2 - 1} - \cos^{-1} (1/q) \right)</math>'],
  ),
                            
  Parameter(
    name     = 'Booster extraction slip factor',
    group    = 'FAC',
    value    = Prms.bo_extraction_slip_factor,
    symbol   = r'<math>\eta</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = ['Booster extraction linear momentum compaction',
                'Booster extraction beam gamma factor'],
    obs      = [r'<math>\eta = \alpha_1 - \frac{1}{\gamma^2}</math>'],
  ),
 
  Parameter(
    name     = 'Booster extraction natural bunch length',
    group    = 'FAC',
    value    = Prms.bo_extraction_natural_bunch_length,
    symbol   = r'<math>\sigma_s</math>',
    units    = 'mm',
    revision = '2014-08-01',
    deps     = ['Booster extraction slip factor',
                'Booster extraction synchrotron frequency',
                'Booster extraction natural energy spread'],
    obs      = [r'<math>\sigma_s = \frac{c |\eta|}{2 \pi f_s} \sigma_\delta</math>'],
  ),

  Parameter(
    name     = 'Booster extraction natural bunch duration',
    group    = 'FAC',
    value    = Prms.bo_extraction_natural_bunch_duration,
    symbol   = r'<math>\sigma_\tau</math>',
    units    = 'ps',
    revision = '2014-08-01',
    deps     = ['Booster extraction natural bunch length',
                'Booster extraction beam beta factor'],
    obs      = [r'<math>\sigma_\tau = \frac{\sigma_s}{\beta c}</math>'],
  ),

  Parameter(
    name     = 'Booster number of beam position monitors',
    group    = 'FAC',
    value    = Prms.bo_number_of_beam_position_monitors,
    symbol   = r'<math>N_\text{BPM}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster number of horizontal correctors',
    group    = 'FAC',
    value    = Prms.bo_number_of_horizontal_correctors,
    symbol   = r'<math>N_\text{CH}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster number of vertical correctors',
    group    = 'FAC',
    value    = Prms.bo_number_of_vertical_correctors,
    symbol   = r'<math>N_\text{CV}</math>',
    units    = '',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster horizontal corrector maximum strength',
    group    = 'FAC',
    value    = Prms.bo_horizontal_corrector_maximum_strength,
    symbol   = r'<math>\theta_\text{CH,max}</math>',
    units    = 'mrad',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

  Parameter(
    name     = 'Booster vertical corrector maximum strength',
    group    = 'FAC',
    value    = Prms.bo_vertical_corrector_maximum_strength,
    symbol   = r'<math>\theta_\text{CV,max}</math>',
    units    = 'mrad',
    revision = '2014-08-01',
    deps     = [],
    obs      = [],
  ),

]
