
TABLE = {
    'Linac multi-bunch beam energy': 'LI beam energy',
    'Linac multi-bunch RF frequency': 'LI rf frequency',
    'Linac multi-bunch maximum normalized emittance': 'LI optics maximum normalized emittance',
    'Linac multi-bunch maximum rms energy spread': 'LI optics maximum rms energy spread',
    'Linac multi-bunch maximum pulse to pulse energy variation': 'LI error maximum pulse to pulse energy variation',
    'Linac multi-bunch maximum pulse to pulse jitter': 'LI error maximum pulse to pulse jitter',
    'Linac multi-bunch minimum pulse charge': 'LI beam multi-bunch minimum pulse charge',
    'Linac multi-bunch minimum pulse duration': 'LI beam multi-bunch minimum pulse duration',
    'Linac multi-bunch maximum pulse duration': 'LI beam multi-bunch maximum pulse duration',
    'Linac multi-bunch repetition rate': 'LI repetition rate',
    'Linac single-bunch beam energy': 'LI beam energy',
    'Linac single-bunch RF frequency': 'LI rf frequency',
    'Linac single-bunch maximum normalized emittance': 'LI optics maximum normalized emittance',
    'Linac single-bunch maximum rms energy spread': 'LI optics maximum rms energy spread',
    'Linac single-bunch maximum pulse to pulse energy variation': 'LI error maximum pulse to pulse energy variation',
    'Linac single-bunch maximum pulse to pulse jitter': 'LI error maximum pulse to pulse jitter',
    'Linac single-bunch minimum pulse charge': 'LI beam single-bunch minimum pulse charge',
    'Linac single-bunch maximum pulse duration': 'LI beam single-bunch maximum pulse duration',
    'Linac single-bunch repetition rate': 'LI repetition rate',

    'Linac to booster transport line beam energy': 'TB beam energy',
    'Linac to booster transport line beam gamma factor': 'TB beam gamma factor',
    'Linac to booster transport line beam beta factor': 'TB beam beta factor',
    'Linac to booster transport line beam velocity': 'TB beam velocity',
    'Linac to booster transport line beam magnetic rigidity': 'TB beam magnetic rigidity',
    'Linac to booster transport line total length': 'TB lattice length',
    'Linac to booster transport line number of dipoles': 'TB magnet dipole number',
    'Linac to booster transport line number of quadrupoles': 'TB magnet quadrupole number',
    'Linac to booster transport line number of septa': 'TB magnet septum number',
    'Linac to booster transport line maximum quadrupole gradient': 'TB magnet quadrupole maximum gradient',
    'Linac to booster transport line deflection angle of dipole': 'TB magnet dipole deflection angle',
    'Linac to booster transport line deflection angle of septum': 'TB magnet septum deflection angle',
    'Linac to booster transport line arc length of dipole': 'TB magnet dipole arc length',
    'Linac to booster transport line arc length of septum': 'TB magnet septum arc length',
    'Linac to booster transport line dipole bending radius': 'TB magnet dipole bending radius',
    'Linac to booster transport line septum bending radius': 'TB magnet septum bending radius',
    'Linac to booster transport line dipole magnetic field': 'TB magnet dipole magnetic field',
    'Linac to booster transport line septum magnetic field': 'TB magnet septum magnetic field',
    'Linac to booster transport line dipole sagitta': 'TB magnet dipole sagitta',
    'Linac to booster transport line septum sagitta': 'TB magnet septum sagitta',
    'Linac to booster transport line hardedge length of QA1 quadrupoles': 'TB magnet quadrupole qa1 hardedge length',
    'Linac to booster transport line hardedge length of QA2 quadrupoles': 'TB magnet quadrupole qa2 hardedge length',
    'Linac to booster transport line hardedge length of QA3 quadrupoles': 'TB magnet quadrupole qa3 hardedge length',
    'Linac to booster transport line hardedge length of QB1 quadrupoles': 'TB magnet quadrupole qb1 hardedge length',
    'Linac to booster transport line hardedge length of QB2 quadrupoles': 'TB magnet quadrupole qb2 hardedge length',
    'Linac to booster transport line hardedge length of QC1 quadrupoles': 'TB magnet quadrupole qc1 hardedge length',
    'Linac to booster transport line hardedge length of QC2 quadrupoles': 'TB magnet quadrupole qc2 hardedge length',
    'Linac to booster transport line hardedge length of QC3 quadrupoles': 'TB magnet quadrupole qc3 hardedge length',
    'Linac to booster transport line hardedge length of QD1 quadrupoles': 'TB magnet quadrupole qd1 hardedge length',
    'Linac to booster transport line hardedge length of QD2 quadrupoles': 'TB magnet quadrupole qd2 hardedge length',
    'Linac to booster transport line hardedge length of QE1 quadrupoles': 'TB magnet quadrupole qe1 hardedge length',
    'Linac to booster transport line hardedge length of QE2 quadrupoles': 'TB magnet quadrupole qe2 hardedge length',

    'Booster lattice version': 'BO lattice version',
    'Booster circumference': 'BO lattice circumference',
    'Booster lattice symmetry': 'BO lattice symmetry',

    'Booster cycling frequency': 'BO ramp cycling frequency',

    'Booster beam current': 'BO beam extraction current',

    'Booster optics mode': 'BO optics default mode',
    'Booster horizontal betatron tune': 'BO optics tune horizontal',
    'Booster vertical betatron tune': 'BO optics tune vertical',
    'Booster extraction synchrotron tune': 'BO optics extraction tune synchrotron',
    'Booster horizontal natural chromaticity': 'BO optics natural chromaticity horizontal',
    'Booster vertical natural chromaticity': 'BO optics natural chromaticity vertical',

    'Booster injection beam energy': 'BO beam injection energy',
    'Booster injection beam gamma factor': 'BO beam injection gamma factor',
    'Booster injection beam beta factor': 'BO beam injection beta factor',
    'Booster injection beam velocity': 'BO beam injection velocity',
    'Booster injection beam magnetic rigidity': 'BO beam injection magnetic rigidity',

    'Booster extraction beam energy': 'BO beam extraction energy',
    'Booster extraction beam gamma factor': 'BO beam extraction gamma factor',
    'Booster extraction beam beta factor': 'BO beam extraction beta factor',
    'Booster extraction beam velocity': 'BO beam extraction velocity',
    'Booster extraction beam magnetic rigidity': 'BO beam extraction magnetic rigidity',
    'Booster extraction revolution period': 'BO beam extraction revolution period',
    'Booster extraction revolution frequency': 'BO beam extraction revolution frequency',

    'Booster harmonic number': 'BO rf harmonic number',
    'Booster extraction RF frequency': 'BO rf extraction frequency',
    'Booster RF cavity peak voltage': 'BO rf extraction peak voltage',
    'Booster extraction RF wavelength': 'BO rf extraction wavelength',

    'Booster number of dipoles': 'BO magnet dipole number',
    'Booster deflection angle of dipoles': 'BO magnet dipole deflection angle',
    'Booster hardedge length of dipoles': 'BO magnet dipole hardedge length',
    'Booster hardedge sagitta of dipoles': 'BO magnet dipole hardedge sagitta',
    'Booster dipole quadrupole integrated strength': 'BO magnet dipole integrated quadrupole strength',
    'Booster dipole sextupole integrated strength': 'BO magnet dipole integrated sextupole strength',
    'Booster dipole bending radius': 'BO magnet dipole hardedge bending radius',
    'Booster dipole quadrupole strength': 'BO magnet dipole hardedge quadrupole strength',
    'Booster dipole sextupole strength': 'BO magnet dipole hardedge sextupole strength',
    'Booster dipole extraction integrated field': 'BO magnet dipole extraction integrated field',

    'Booster extraction dipole integrated field': 'BO magnet dipole extraction integrated field',
    'Booster extraction dipole magnetic field': 'BO magnet dipole extraction hardedge magnetic field',
    'Booster extraction dipole quadrupole integrated gradient': 'BO magnet dipole extraction quadrupole integrated gradient',
    'Booster extraction dipole quadrupole gradient': 'BO magnet dipole extraction quadrupole gradient',
    'Booster extraction dipole sextupole integrated gradient': 'BO magnet dipole extraction sextupole integrated gradient',
    'Booster extraction dipole sextupole gradient': 'BO magnet dipole extraction sextupole gradient',

    'Booster injection dipole integrated field': 'BO magnet dipole injection integrated field',
    'Booster injection dipole magnetic field': 'BO magnet dipole injection hardedge magnetic field',
    'Booster injection dipole quadrupole integrated gradient': 'BO magnet dipole injection quadrupole integrated gradient',
    'Booster injection dipole sextupole integrated gradient': 'BO magnet dipole injection sextupole integrated gradient',
    'Booster injection dipole quadrupole gradient': 'BO magnet dipole injection quadrupole gradient',
    'Booster injection dipole sextupole gradient': 'BO magnet dipole injection sextupole gradient',

    'Booster extraction radiation integral I1': 'BO optics extraction radiation integral i1',
    'Booster extraction radiation integral I2': 'BO optics extraction radiation integral i2',
    'Booster extraction radiation integral I3': 'BO optics extraction radiation integral i3',
    'Booster extraction radiation integral I4': 'BO optics extraction radiation integral i4',
    'Booster extraction radiation integral I5': 'BO optics extraction radiation integral i5',
    'Booster extraction radiation integral I6': 'BO optics extraction radiation integral i6',

    'Booster extraction energy loss per turn': 'BO optics extraction energy loss per turn',
    'Booster extraction horizontal damping partition number': 'BO optics extraction damping partition number horizontal',
    'Booster extraction vertical damping partition number': 'BO optics extraction damping partition number vertical',
    'Booster extraction longitudinal damping partition number': 'BO optics extraction damping partition number longitudinal',
    'Booster extraction horizontal radiation damping time': 'BO optics extraction radiation damping time horizontal',
    'Booster extraction vertical radiation damping time': 'BO optics extraction radiation damping time vertical',
    'Booster extraction longitudinal radiation damping time': 'BO optics extraction radiation damping time longitudinal',

    'Booster extraction linear momentum compaction': 'BO optics extraction linear momentum compaction',
    'Booster extraction radiation power': 'BO optics extraction radiation power',
    'Booster extraction natural emittance': 'BO optics extraction natural emittance',
    'Booster extraction natural energy spread': 'BO optics extraction natural energy spread',

    'Booster extraction overvoltage': 'BO optics extraction overvoltage',
    'Booster extraction synchronous phase': 'BO optics extraction synchronous phase',
    'Booster extraction synchrotron frequency': 'BO optics extraction synchrotron frequency',
    'Booster extraction RF energy acceptance': 'BO optics extraction rf energy acceptance',
    'Booster extraction slip factor': 'BO optics extraction slip factor',
    'Booster extraction natural bunch length': 'BO optics extraction natural bunch length',
    'Booster extraction natural bunch duration': 'BO optics extraction natural bunch duration',

    'Booster number of QF quadrupoles': 'BO magnet quadrupole qf number',
    'Booster hardedge length of QF quadrupoles': 'BO magnet quadrupole qf hardedge length',
    'Booster QF quadrupole maximum strength': 'BO magnet quadrupole qf maximum strength',
    'Booster injection QF quadrupole maximum gradient': 'BO magnet quadrupole injection qf maximum gradient',
    'Booster extraction QF quadrupole maximum gradient': 'BO magnet quadrupole extraction qf maximum gradient',

    'Booster number of QD quadrupoles': 'BO magnet quadrupole qd number',
    'Booster hardedge length of QD quadrupoles': 'BO magnet quadrupole qd hardedge length',
    'Booster QD quadrupole maximum strength': 'BO magnet quadrupole qd maximum strength',
    'Booster injection QD quadrupole maximum gradient': 'BO magnet quadrupole injection qd maximum gradient',
    'Booster extraction QD quadrupole maximum gradient': 'BO magnet quadrupole extraction qd maximum gradient',

    'Booster number of SF sextupoles': 'BO magnet sextupole sf number',
    'Booster hardedge length of SF sextupoles': 'BO magnet sextupole sf hardedge length',
    'Booster SF sextupole maximum strength': 'BO magnet sextupole sf maximum strength',
    'Booster injection SF sextupole maximum gradient': 'BO magnet sextupole injection sf maximum gradient',
    'Booster extraction SF sextupole maximum gradient': 'BO magnet sextupole extraction sf maximum gradient',

    'Booster number of SD sextupoles': 'BO magnet sextupole sd number',
    'Booster hardedge length of SD sextupoles': 'BO magnet sextupole sd hardedge length',
    'Booster SD sextupole maximum strength': 'BO magnet sextupole sd maximum strength',
    'Booster injection SD sextupole maximum gradient': 'BO magnet sextupole injection sd maximum gradient',
    'Booster extraction SD sextupole maximum gradient': 'BO magnet sextupole extraction sd maximum gradient',

    'Booster number of beam position monitors': 'BO bpm number',
    'Booster number of horizontal dipole correctors': 'BO magnet ch number',
    'Booster horizontal dipole corrector maximum strength': 'BO magnet ch maximum normalized integrated field',
    'Booster number of vertical dipole correctors': 'BO magnet cv number',
    'Booster vertical dipole corrector maximum strength': 'BO magnet cv maximum normalized integrated field',

    'Booster beam position monitors alignment error tolerance': 'BO error alignment bpm',

    'Booster dipoles alignment error tolerance': 'BO error alignment dipole',
    'Booster dipoles excitation error tolerance': 'BO error excitation dipole',
    'Booster dipoles rotation error tolerance': 'BO error rotation dipole',

    'Booster quadrupoles alignment error tolerance': 'BO error alignment quadrupole',
    'Booster quadrupoles excitation error tolerance': 'BO error excitation quadrupole',
    'Booster quadrupoles rotation error tolerance': 'BO error rotation quadrupole',

    'Booster sextupoles alignment error tolerance': 'BO error alignment sextupole',
    'Booster sextupoles excitation error tolerance': 'BO error excitation sextupole',
    'Booster sextupoles rotation error tolerance': 'BO error rotation sextupole',

    'Booster reference position for multipole contribution for dipoles': 'BO error multipole dipole reference position',

    'Booster systematic normal 8-pole error tolerance for dipoles': 'BO error multipole dipole systematic normal 8-pole',
    'Booster systematic normal 10-pole error tolerance for dipoles': 'BO error multipole dipole systematic normal 10-pole',
    'Booster systematic normal 12-pole error tolerance for dipoles': 'BO error multipole dipole systematic normal 12-pole',
    'Booster systematic normal 14-pole error tolerance for dipoles': 'BO error multipole dipole systematic normal 14-pole',

    'Booster random normal 6-pole error tolerance for dipoles': 'BO error multipole dipole random normal 6-pole',
    'Booster random normal 8-pole error tolerance for dipoles': 'BO error multipole dipole random normal 8-pole',
    'Booster random normal 10-pole error tolerance for dipoles': 'BO error multipole dipole random normal 10-pole',
    'Booster random normal 12-pole error tolerance for dipoles': 'BO error multipole dipole random normal 12-pole',
    'Booster random normal 14-pole error tolerance for dipoles': 'BO error multipole dipole random normal 14-pole',
    'Booster random normal 16-pole error tolerance for dipoles': 'BO error multipole dipole random normal 16-pole',
    'Booster random normal 18-pole error tolerance for dipoles': 'BO error multipole dipole random normal 18-pole',

    'Booster random skew 6-pole error tolerance for dipoles': 'BO error multipole dipole random skew 6-pole',
    'Booster random skew 8-pole error tolerance for dipoles': 'BO error multipole dipole random skew 8-pole',
    'Booster random skew 10-pole error tolerance for dipoles': 'BO error multipole dipole random skew 10-pole',
    'Booster random skew 12-pole error tolerance for dipoles': 'BO error multipole dipole random skew 12-pole',
    'Booster random skew 14-pole error tolerance for dipoles': 'BO error multipole dipole random skew 14-pole',
    'Booster random skew 16-pole error tolerance for dipoles': 'BO error multipole dipole random skew 16-pole',
    'Booster random skew 18-pole error tolerance for dipoles': 'BO error multipole dipole random skew 18-pole',

    'Booster reference position for multipole contribution for quadrupoles': 'BO error multipole quadrupole reference position',

    'Booster systematic normal 12-pole error tolerance for quadrupoles': 'BO error multipole quadrupole systematic normal 12-pole',
    'Booster systematic normal 20-pole error tolerance for quadrupoles': 'BO error multipole quadrupole systematic normal 20-pole',
    'Booster systematic normal 28-pole error tolerance for quadrupoles': 'BO error multipole quadrupole systematic normal 28-pole',

    'Booster random normal 6-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random normal 6-pole',
    'Booster random normal 8-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random normal 8-pole',
    'Booster random normal 10-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random normal 10-pole',
    'Booster random normal 12-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random normal 12-pole',
    'Booster random normal 14-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random normal 14-pole',
    'Booster random normal 16-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random normal 16-pole',
    'Booster random normal 18-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random normal 18-pole',
    'Booster random normal 20-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random normal 20-pole',

    'Booster random skew 6-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random skew 6-pole',
    'Booster random skew 8-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random skew 8-pole',
    'Booster random skew 10-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random skew 10-pole',
    'Booster random skew 12-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random skew 12-pole',
    'Booster random skew 14-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random skew 14-pole',
    'Booster random skew 16-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random skew 16-pole',
    'Booster random skew 18-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random skew 18-pole',
    'Booster random skew 20-pole error tolerance for quadrupoles': 'BO error multipole quadrupole random skew 20-pole',

    'Booster reference position for multipole contribution for sextupoles': 'BO error multipole sextupole reference position',

    'Booster systematic normal 18-pole error tolerance for sextupoles': 'BO error multipole sextupole systematic normal 18-pole',
    'Booster systematic normal 30-pole error tolerance for sextupoles': 'BO error multipole sextupole systematic normal 30-pole',

    'Booster random normal 8-pole error tolerance for sextupoles': 'BO error multipole sextupole random normal 8-pole',
    'Booster random normal 10-pole error tolerance for sextupoles': 'BO error multipole sextupole random normal 10-pole',
    'Booster random normal 12-pole error tolerance for sextupoles': 'BO error multipole sextupole random normal 12-pole',
    'Booster random normal 14-pole error tolerance for sextupoles': 'BO error multipole sextupole random normal 14-pole',
    'Booster random normal 16-pole error tolerance for sextupoles': 'BO error multipole sextupole random normal 16-pole',
    'Booster random normal 18-pole error tolerance for sextupoles': 'BO error multipole sextupole random normal 18-pole',
    'Booster random normal 20-pole error tolerance for sextupoles': 'BO error multipole sextupole random normal 20-pole',

    'Booster random skew 8-pole error tolerance for sextupoles': 'BO error multipole sextupole random skew 8-pole',
    'Booster random skew 10-pole error tolerance for sextupoles': 'BO error multipole sextupole random skew 10-pole',
    'Booster random skew 12-pole error tolerance for sextupoles': 'BO error multipole sextupole random skew 12-pole',
    'Booster random skew 14-pole error tolerance for sextupoles': 'BO error multipole sextupole random skew 14-pole',
    'Booster random skew 16-pole error tolerance for sextupoles': 'BO error multipole sextupole random skew 16-pole',
    'Booster random skew 18-pole error tolerance for sextupoles': 'BO error multipole sextupole random skew 18-pole',
    'Booster random skew 20-pole error tolerance for sextupoles': 'BO error multipole sextupole random skew 20-pole',

    'Booster to storage ring transport line beam energy': 'TS beam energy',
    'Booster to storage ring transport line beam gamma factor': 'TS beam gamma factor',
    'Booster to storage ring transport line beam beta factor': 'TS beam beta factor',
    'Booster to storage ring transport line beam velocity': 'TS beam velocity',
    'Booster to storage ring transport line beam magnetic rigidity': 'TS beam magnetic rigidity',
    'Booster to storage ring transport line total length': 'TS lattice length',
    'Booster to storage ring transport line number of dipoles': 'TS magnet dipole number',
    'Booster to storage ring transport line number of quadrupoles': 'TS magnet quadrupole number',
    'Booster to storage ring transport line maximum quadrupole gradient': 'TS magnet quadrupole maximum gradient',
    'Booster to storage ring transport line hardedge length of dipoles': 'TS magnet dipole hardedge length',
    'Booster to storage ring transport line hardedge length of extraction septum': 'TS magnet extraction septum hardedge length',
    'Booster to storage ring transport line hardedge length of thick injection septum': 'TS magnet thick injection septum hardedge length',
    'Booster to storage ring transport line hardedge length of thin injection septum': 'TS magnet thin injection septum hardedge length',
    'Booster to storage ring transport line deflection angle of dipoles': 'TS magnet dipole deflection angle',
    'Booster to storage ring transport line deflection angle of extraction septum': 'TS magnet extraction septum deflection angle',
    'Booster to storage ring transport line deflection angle of thick injection septum': 'TS magnet thick injection septum deflection angle',
    'Booster to storage ring transport line deflection angle of thin injection septum': 'TS magnet thin injection septum deflection angle',
    'Booster to storage ring transport line dipole bending radius': 'TS magnet dipole hardedge bending radius',
    'Booster to storage ring transport line extraction septum bending radius': 'TS magnet extraction septum hardedge bending radius',
    'Booster to storage ring transport line thick injection septum bending radius': 'TS magnet thick injection septum hardedge bending radius',
    'Booster to storage ring transport line thin injection septum bending radius': 'TS magnet thin injection septum hardedge bending radius',
    'Booster to storage ring transport line dipole magnetic field': 'TS magnet dipole hardedge magnetic field',
    'Booster to storage ring transport line extraction septum magnetic field': 'TS magnet extraction septum hardedge magnetic field',
    'Booster to storage ring transport line thick injection septum magnetic field': 'TS magnet thick injection septum hardedge magnetic field',
    'Booster to storage ring transport line thin injection septum magnetic field': 'TS magnet thin injection septum hardedge magnetic field',
    'Booster to storage ring transport line dipole sagitta': 'TS magnet dipole hardedge sagitta',
    'Booster to storage ring transport line extraction septum sagitta': 'TS magnet extraction septum hardedge sagitta',
    'Booster to storage ring transport line thick injection septum sagitta': 'TS magnet thick injection septum hardedge sagitta',
    'Booster to storage ring transport line thin injection septum sagitta': 'TS magnet thin injection septum hardedge sagitta',
    'Booster to storage ring transport line number of extraction septa': 'TS magnet extraction setpum number',
    'Booster to storage ring transport line number of thick injection septa': 'TS magnet thick injection septum number',
    'Booster to storage ring transport line number of thin injection septa': 'TS magnet thin injection septum number',
    'Booster to storage ring transport line hardedge length of QA1 quadrupoles': 'TS magnet quadrupole hardedge length',
    'Booster to storage ring transport line hardedge length of QA2 quadrupoles': 'TS magnet quadrupole hardedge length',
    'Booster to storage ring transport line hardedge length of QB1 quadrupoles': 'TS magnet quadrupole hardedge length',
    'Booster to storage ring transport line hardedge length of QB2 quadrupoles': 'TS magnet quadrupole hardedge length',
    'Booster to storage ring transport line hardedge length of QC1 quadrupoles': 'TS magnet quadrupole hardedge length',
    'Booster to storage ring transport line hardedge length of QC2 quadrupoles': 'TS magnet quadrupole hardedge length',
    'Booster to storage ring transport line hardedge length of QC3 quadrupoles': 'TS magnet quadrupole hardedge length',
    'Booster to storage ring transport line hardedge length of QC4 quadrupoles': 'TS magnet quadrupole hardedge length',
    'Booster to storage ring transport line QA1 quadrupole strength': 'TS magnet quadrupole hardedge strength',
    'Booster to storage ring transport line QA2 quadrupole strength': 'TS magnet quadrupole hardedge strength',
    'Booster to storage ring transport line QB1 quadrupole strength': 'TS magnet quadrupole hardedge strength',
    'Booster to storage ring transport line QB2 quadrupole strength': 'TS magnet quadrupole hardedge strength',
    'Booster to storage ring transport line QC1 quadrupole strength': 'TS magnet quadrupole hardedge strength',
    'Booster to storage ring transport line QC2 quadrupole strength': 'TS magnet quadrupole hardedge strength',
    'Booster to storage ring transport line QC3 quadrupole strength': 'TS magnet quadrupole hardedge strength',
    'Booster to storage ring transport line QC4 quadrupole strength': 'TS magnet quadrupole hardedge strength',
    'Booster to storage ring transport line QA1 quadrupole gradient': 'TS magnet quadrupole hardedge gradient',
    'Booster to storage ring transport line QA2 quadrupole gradient': 'TS magnet quadrupole hardedge gradient',
    'Booster to storage ring transport line QB1 quadrupole gradient': 'TS magnet quadrupole hardedge gradient',
    'Booster to storage ring transport line QB2 quadrupole gradient': 'TS magnet quadrupole hardedge gradient',
    'Booster to storage ring transport line QC1 quadrupole gradient': 'TS magnet quadrupole hardedge gradient',
    'Booster to storage ring transport line QC2 quadrupole gradient': 'TS magnet quadrupole hardedge gradient',
    'Booster to storage ring transport line QC3 quadrupole gradient': 'TS magnet quadrupole hardedge gradient',
    'Booster to storage ring transport line QC4 quadrupole gradient': 'TS magnet quadrupole hardedge gradient',
    'Booster to storage ring transport line number of beam position monitors': 'TS bpm number',
    'Booster to storage ring transport line number of horizontal dipole correctors': 'TS magnet hcm number',
    'Booster to storage ring transport line number of vertical dipole correctors': 'TS magnet vcm number',
    'Booster to storage ring transport line horizontal dipole correctors maximum strength': 'TS magnet hcm maximum strength',
    'Booster to storage ring transport line vertical dipole correctors maximum strength': 'TS magnet vcm maximum strength',

    'Storage ring lattice version': 'SI lattice version',
    'Storage ring lattice type': 'SI lattice type',
    'Storage ring lattice circumference': 'SI lattice circumference',
    'Storage ring lattice symmetry': 'SI lattice symmetry',
    'Storage ring number of long straight sections': 'SI lattice long straight section number',
    'Storage ring number of short straight sections': 'SI lattice short straight section number',
    'Storage ring length of long straight sections': 'SI lattice long straight section length',
    'Storage ring length of short straight sections': 'SI lattice short straight section length',

    'Storage ring beam energy': 'SI beam energy',
    'Storage ring beam current': 'SI beam current',
    'Storage ring beam gamma factor': 'SI beam gamma factor',
    'Storage ring beam beta factor': 'SI beam beta factor',
    'Storage ring beam velocity': 'SI beam velocity',
    'Storage ring beam magnetic rigidity': 'SI beam magnetic rigidity',
    'Storage ring revolution period': 'SI beam revolution period',
    'Storage ring revolution frequency': 'SI beam revolution frequency',

    'Storage ring number of electrons': 'SI beam electron number',
    'Storage ring harmonic number': 'SI rf harmonic number',
    'Storage ring RF frequency': 'SI rf frequency',
    'Storage ring  RF cavity peak voltage': 'SI rf peak voltage',
    'Storage ring RF cavity peak voltage': 'SI rf peak voltage',

    'Storage ring number of B1 dipoles': 'SI magnet dipole b1 number',
    'Storage ring deflection angle of B1 dipoles': 'SI magnet dipole b1 deflection angle',
    'Storage ring hardedge length of B1 dipoles': 'SI magnet dipole b1 hardedge length',
    'Storage ring B1 dipole bending radius': 'SI magnet dipole b1 hardedge bending radius',
    'Storage ring B1 dipole magnetic field': 'SI magnet dipole b1 hardedge magnetic field',
    'Storage ring B1 dipole critical energy': 'SI magnet dipole b1 hardedge critical energy',
    'Storage ring hardedge sagitta of B1 dipoles': 'SI magnet dipole b1 hardedge sagitta',
    'Storage ring number of B2 dipoles': 'SI magnet dipole b2 number',
    'Storage ring deflection angle of B2 dipoles': 'SI magnet dipole b2 deflection angle',
    'Storage ring hardedge length of B2 dipoles': 'SI magnet dipole b2 hardedge length',
    'Storage ring B2 dipole bending radius': 'SI magnet dipole b2 hardedge bending radius',
    'Storage ring B2 dipole magnetic field': 'SI magnet dipole b2 hardedge magnetic field',
    'Storage ring B2 dipole critical energy': 'SI magnet dipole b2 hardedge critical energy',
    'Storage ring hardedge sagitta of B2 dipoles': 'SI magnet dipole b2 hardedge sagitta',
    'Storage ring number of B3 dipoles': 'SI magnet dipole b3 number',
    'Storage ring deflection angle of B3 dipoles': 'SI magnet dipole b3 deflection angle',
    'Storage ring hardedge length of B3 dipoles': 'SI magnet dipole b3 hardedge length',
    'Storage ring B3 dipole bending radius': 'SI magnet dipole b3 hardedge bending radius',
    'Storage ring B3 dipole magnetic field': 'SI magnet dipole b3 hardedge magnetic field',
    'Storage ring B3 dipole critical energy': 'SI magnet dipole b3 hardedge critical energy',
    'Storage ring number of BC dipoles': 'SI magnet dipole bc number',
    'Storage ring hardedge sagitta of B3 dipoles': 'SI magnet dipole b3 hardedge sagitta',
    'Storage ring deflection angle of BC dipoles': 'SI magnet dipole bc deflection angle',
    'Storage ring hardedge length of BC dipoles': 'SI magnet dipole bc hardedge length',
    'Storage ring BC dipole bending radius': 'SI magnet dipole bc hardedge bending radius',
    'Storage ring BC dipole magnetic field': 'SI magnet dipole bc hardedge magnetic field',
    'Storage ring BC dipole critical energy': 'SI magnet dipole bc hardedge critical energy',
    'Storage ring hardedge sagitta of BC dipoles': 'SI magnet dipole bc hardedge sagitta',

    'Storage ring number of beam position monitors': 'SI bpm number',
    'Storage ring number of horizontal slow dipole correctors': 'SI magnet chs number',
    'Storage ring number of vertical slow dipole correctors': 'SI magnet cvs number',
    'Storage ring number of horizontal fast dipole correctors': 'SI magnet chf number',
    'Storage ring number of vertical fast dipole correctors': 'SI magnet cvf number',
    'Storage ring number of skew quadrupoles': 'SI magnet qs number',
    'Storage ring horizontal slow dipole corrector maximum strength': 'SI magnet chs maximum normalized integrated field',
    'Storage ring vertical slow dipole corrector maximum strength': 'SI magnet cvs maximum normalized integrated field',
    'Storage ring horizontal fast dipole corrector maximum strength': 'SI magnet chf maximum normalized integrated field',
    'Storage ring vertical fast dipole corrector maximum strength': 'SI magnet cvf maximum normalized integrated field',
    'Storage ring skew corrector maximum integrated strength': 'SI magnet qs maximum integrated strength',
    'Storage ring skew quadrupole maximum integrated strength': 'SI magnet qs maximum integrated strength',

    'Storage ring optics mode': 'SI optics default mode',
    'Storage ring horizontal tune': 'SI optics tune horizontal',
    'Storage ring vertical tune': 'SI optics tune vertical',
    'Storage ring synchrotron tune from dipoles': 'SI optics tune synchrotron dipole',
    'Storage ring synchrotron tune': 'SI optics tune synchrotron',
    'Storage ring horizontal betatron frequency': 'SI optics betatron frequency horizontal',
    'Storage ring vertical betatron frequency': 'SI optics betatron frequency vertical',
    'Storage ring synchrotron frequency': 'SI optics synchrotron frequency',

    'Storage ring natural horizontal linear chromaticity': 'SI optics natural linear chromaticity horizontal',
    'Storage ring horizontal natural chromaticity':      'SI optics natural linear chromaticity horizontal',
    'Storage ring natural vertical linear chromaticity': 'SI optics natural linear chromaticity vertical',
    'Storage ring vertical natural linear chromaticity': 'SI optics natural linear chromaticity vertical',
    'Storage ring vertical natural chromaticity': 'SI optics natural linear chromaticity vertical',

    'Storage ring horizontal beam size at center of long straight sections': 'SI optics beam size horizontal long straight section',
    'Storage ring horizontal beam size at center of long straight section': 'SI optics beam size horizontal long straight section',
    'Storage ring horizontal beam size at center of short straight sections': 'SI optics beam size horizontal short straight section',
    'Storage ring horizontal beam size at center of short straight section': 'SI optics beam size horizontal short straight section',
    'Storage ring vertical beam size at center of long straight sections': 'SI optics beam size vertical long straight section',
    'Storage ring vertical beam size at center of long straight section': 'SI optics beam size vertical long straight section',
    'Storage ring vertical beam size at center of short straight sections': 'SI optics beam size vertical short straight section',
    'Storage ring vertical beam size at center of short straight section': 'SI optics beam size vertical short straight section',
    'Storage ring horizontal beam size at center of superbend': 'SI optics beam size horizontal dipole bc',
    'Storage ring horizontal beam size at center of BC dipoles': 'SI optics beam size horizontal dipole bc',
    'Storage ring vertical beam size at center of superbend': 'SI optics beam size vertical dipole bc',
    'Storage ring vertical beam size at center of BC dipoles': 'SI optics beam size vertical dipole bc',

    'Storage ring horizontal beam divergence at center of long straight sections': 'SI optics beam divergence horizontal long straight section',
    'Storage ring horizontal beam divergence at center of long straight section': 'SI optics beam divergence horizontal long straight section',
    'Storage ring horizontal beam divergence at center of short straight sections': 'SI optics beam divergence horizontal short straight section',
    'Storage ring horizontal beam divergence at center of short straight section': 'SI optics beam divergence horizontal short straight section',
    'Storage ring vertical beam divergence at center of long straight sections': 'SI optics beam divergence vertical long straight section',
    'Storage ring vertical beam divergence at center of long straight section': 'SI optics beam divergence vertical long straight section',
    'Storage ring vertical beam divergence at center of short straight sections': 'SI optics beam divergence vertical short straight section',
    'Storage ring vertical beam divergence at center of short straight section': 'SI optics beam divergence vertical short straight section',
    'Storage ring horizontal beam divergence at center of superbend': 'SI optics beam divergence horizontal dipole bc',
    'Storage ring horizontal beam divergence at center of BC dipoles': 'SI optics beam divergence horizontal dipole bc',
    'Storage ring vertical beam divergence at center of superbend': 'SI optics beam divergence vertical dipole bc',
    'Storage ring vertical beam divergence at center of BC dipoles': 'SI optics beam divergence vertical dipole bc',

    'Storage ring radiation integral I1 from dipoles': 'SI optics radiation integral i1 dipole',
    'Storage ring radiation integral I2 from dipoles': 'SI optics radiation integral i2 dipole',
    'Storage ring radiation integral I3 from dipoles': 'SI optics radiation integral i3 dipole',
    'Storage ring radiation integral I4 from dipoles': 'SI optics radiation integral i4 dipole',
    'Storage ring radiation integral I5 from dipoles': 'SI optics radiation integral i5 dipole',
    'Storage ring radiation integral I6 from dipoles': 'SI optics radiation integral i6 dipole',
    'Storage ring radiation integral I1 from IDs': 'SI optics radiation integral i1 id',
    'Storage ring radiation integral I2 from IDs': 'SI optics radiation integral i2 id',
    'Storage ring radiation integral I3 from IDs': 'SI optics radiation integral i3 id',
    'Storage ring radiation integral I4 from IDs': 'SI optics radiation integral i4 id',
    'Storage ring radiation integral I5 from IDs': 'SI optics radiation integral i5 id',
    'Storage ring radiation integral I6 from IDs': 'SI optics radiation integral i6 id',
    'Storage ring radiation integral I1': 'SI optics radiation integral i1',
    'Storage ring radiation integral I2': 'SI optics radiation integral i2',
    'Storage ring radiation integral I3': 'SI optics radiation integral i3',
    'Storage ring radiation integral I4': 'SI optics radiation integral i4',
    'Storage ring radiation integral I5': 'SI optics radiation integral i5',
    'Storage ring radiation integral I6': 'SI optics radiation integral i6',
    'Storage ring transverse coupling': 'SI optics transverse coupling',
    'Storage ring horizontal damping partition number from dipoles': 'SI optics damping partition number vertical dipole',
    'Storage ring vertical damping partition number from dipoles': 'SI optics damping partition number horizontal dipole',
    'Storage ring longitudinal damping partition number from dipoles': 'SI optics damping partition number longitudinal dipole',
    'Storage ring energy loss per turn from dipoles': 'SI optics energy loss per turn dipole',
    'Storage ring energy loss per turn dipoles': 'SI optics energy loss per turn dipole',
    'Storage ring radiation power from dipoles': 'SI optics radiation power dipole',
    'Storage ring overvoltage from dipoles ': 'SI optics overvoltage dipole',
    'Storage ring synchronous phase from dipoles': 'SI optics synchronous phase dipole',
    'Storage ring linear momentum compaction from dipoles': 'SI optics linear momentum compaction dipole',
    'Storage ring linear slip phase from dipoles': 'SI optics linear slip phase dipole',
    'Storage ring RF energy acceptance from dipoles': 'SI optics rf energy acceptance dipole',
    'Storage ring natural emittance from dipoles': 'SI optics natural emittance dipole',
    'Storage ring natural energy spread from dipoles': 'SI optics natural energy spread dipole',
    'Storage ring natural bunch length from dipoles': 'SI optics natural bunch length dipole',
    'Storage ring natural bunch duration from dipoles': 'SI optics natural bunch duration dipole',
    'Storage ring horizontal radiation damping time from dipoles': 'SI optics radiation damping time horizontal dipole',
    'Storage ring vertical radiation damping time from dipoles': 'SI optics radiation damping time vertical dipole',
    'Storage ring longitudinal radiation damping time from dipoles': 'SI optics radiation damping time longitudinal dipole',
    'Storage ring energy loss per turn from IDs': 'SI optics energy loss per turn id',
    'Storage ring horizontal damping partition number': 'SI optics damping partition number vertical',
    'Storage ring vertical damping partition number': 'SI optics damping partition number horizontal',
    'Storage ring longitudinal damping partition number': 'SI optics damping partition number longitudinal',
    'Storage ring energy loss per turn': 'SI optics energy loss per turn',
    'Storage ring radiation power': 'SI optics radiation power',
    'Storage ring overvoltage': 'SI optics overvoltage',
    'Storage ring synchronous phase': 'SI optics synchronous phase',
    'Storage ring linear momentum compaction': 'SI optics linear momentum compaction',
    'Storage ring linear slip phase': 'SI optics linear slip phase',
    'Storage ring RF energy acceptance': 'SI optics rf energy acceptance',
    'Storage ring natural emittance': 'SI optics natural emittance',
    'Storage ring natural energy spread': 'SI optics natural energy spread',
    'Storage ring natural bunch length': 'SI optics natural bunch length',
    'Storage ring natural bunch duration': 'SI optics natural bunch duration',
    'Storage ring horizontal radiation damping time': 'SI optics radiation damping time horizontal',
    'Storage ring vertical radiation damping time': 'SI optics radiation damping time vertical',
    'Storage ring longitudinal radiation damping time': 'SI optics radiation damping time longitudinal',
}
