
TABLE = {
    'Booster lattice version': 'BO lattice version',
    #'': 'BO lattice type',
    'Booster circumference': 'BO lattice circumference',
    'Booster lattice symmetry': 'BO lattice symmetry',

    'Booster cycling frequency': 'BO ramp cycling frequency',

    'Booster injection beam energy': 'BO beam injection energy',
    'Booster injection beam gamma factor': 'BO beam injection gamma factor',
    'Booster injection beam beta factor': 'BO beam injection beta factor',
    'Booster injection beam velocity': 'BO beam injection velocity',
    'Booster injection beam magnetic rigidity': 'BO beam injection magnetic rigidity',
    #'Booster beam revolution period': 'BO beam injection revolution period',
    #'Booster injection revolution frequency': 'BO beam injection revolution frequency',
    #'': 'BO beam injection electron number',

    'Booster extraction beam energy': 'BO beam extraction energy',
    'Booster beam current': 'BO beam extraction current',
    'Booster extraction beam gamma factor': 'BO beam extraction gamma factor',
    'Booster extraction beam beta factor': 'BO beam extraction beta factor',
    'Booster extraction beam velocity': 'BO beam extraction velocity',
    'Booster extraction beam magnetic rigidity': 'BO beam extraction magnetic rigidity',
    'Booster extraction revolution period': 'BO beam extraction revolution period',
    'Booster extraction revolution frequency': 'BO beam extraction revolution frequency',
    #'': 'BO beam extraction electron number',

    'Booster harmonic number': 'BO rf harmonic number',
    # '': 'BO rf injection frequency',
    # '': 'BO rf injection peak voltage',
    'Booster extraction RF frequency': 'BO rf extraction frequency',
    'Booster RF cavity peak voltage': 'BO rf extraction peak voltage',

    'Booster number of dipoles': 'BO magnet dipole number',
    'Booster deflection angle of dipoles': 'BO magnet dipole deflection angle',
    'Booster hardedge length of dipoles': 'BO magnet dipole hardedge length',
    'Booster dipole quadrupole integrated strength': 'BO magnet dipole integrated quadrupole strength',
    'Booster dipole sextupole integrated strength': 'BO magnet dipole integrated sextupole strength',

    'Booster dipole bending radius': 'BO magnet dipole hardedge bending radius',
    'Booster hardedge sagitta of dipoles': 'BO magnet dipole hardedge sagitta',
    'Booster dipole quadrupole strength': 'BO magnet dipole hardedge quadrupole strength',
    'Booster dipole sextupole strength': 'BO magnet dipole hardedge sextupole strength',
    'Booster dipole integrated field': 'BO magnet dipole extraction integrated field',

    'Booster injection dipole magnetic field': 'BO magnet dipole injection hardedge magnetic field',
    #'': 'BO magnet dipole injection hardedge critical energy',
    'Booster extraction dipole magnetic field': 'BO magnet dipole extraction hardedge magnetic field',
    #'': 'BO magnet dipole extraction hardedge critical energy',

    'Booster optics mode': 'BO optics default mode',
    'Booster horizontal betatron tune': 'BO optics tune horizontal',
    'Booster vertical betatron tune': 'BO optics tune vertical',
    #'': 'BO optics injection tune synchrotron',
    'Booster extraction synchrotron tune': 'BO optics extraction tune synchrotron',
    #'': 'BO optics chromaticity horizontal',
    #'': 'BO optics chromaticity vertical',
    'Booster horizontal natural chromaticity': 'BO optics natural chromaticity horizontal',
    'Booster vertical natural chromaticity': 'BO optics natural chromaticity vertical',

    #'': 'BO optics injection betatron frequency horizontal',
    #'': 'BO optics extraction betatron frequency horizontal',
    #'': 'BO optics injection betatron frequency vertical',
    #'': 'BO optics extraction betatron frequency vertical',
    'Booster beam position monitors alignment error tolerance': 'BO error alignment bpm',
    'Booster dipoles alignment error tolerance': 'BO error alignment dipole',
    'Booster dipoles excitation error tolerance': 'BO error excitation dipole',
    'Booster dipoles rotation error tolerance': 'BO error rotation dipole',

    'Storage ring lattice version': 'SI lattice version',       
    'Storage ring lattice type': 'SI lattice type',          
    'Storage ring lattice circumference': 'SI lattice circumference', 
    'Storage ring lattice symmetry': 'SI lattice symmetry',      
    'Storage ring number of long straight sections': 'SI lattice long straight section number',  
    'Storage ring number of short straight sections': 'SI lattice short straight section number', 
    'Storage ring length of long straight sections': 'SI lattice long straight section length',  
    'Storage ring length of short straight sections': 'SI lattice short straight section length', 

    'Storage ring beam energy': 'SI beam energy',            
    'Storage ring beam current': 'SI beam current',           
    'Storage ring beam gamma factor': 'SI beam gamma factor',      
    'Storage ring beam beta factor': 'SI beam beta factor',       
    'Storage ring beam velocity': 'SI beam velocity',          
    'Storage ring beam magnetic rigidity': 'SI beam magnetic rigidity', 
    'Storage ring revolution period': 'SI beam revolution period',    
    'Storage ring revolution frequency': 'SI beam revolution frequency', 

    'Storage ring ---': 'SI beam electron number',
    'Storage ring harmonic number': 'SI rf harmonic number', 
    'Storage ring RF frequency': 'SI rf frequency',  
    'Storage ring  RF cavity peak voltage': 'SI rf peak voltage',
    'Storage ring RF cavity peak voltage': 'SI rf peak voltage',  

    'Storage ring number of B1 dipoles': 'SI magnet dipole b1 number',
    'Storage ring deflection angle of B1 dipoles': 'SI magnet dipole b1 deflection angle',
    'Storage ring hardedge length of B1 dipoles': 'SI magnet dipole b1 hardedge length', 
    'Storage ring B1 dipole bending radius': 'SI magnet dipole b1 hardedge bending radius',
    'Storage ring B1 dipole magnetic field': 'SI magnet dipole b1 hardedge magnetic field',
    'Storage ring B1 dipole critical energy': 'SI magnet dipole b1 hardedge critical energy',
    'Storage ring hardedge sagitta of B1 dipoles': 'SI magnet dipole b1 hardedge sagitta',
    'Storage ring number of B2 dipoles': 'SI magnet dipole b2 number',
    'Storage ring deflection angle of B2 dipoles': 'SI magnet dipole b2 deflection angle', 
    'Storage ring hardedge length of B2 dipoles': 'SI magnet dipole b2 hardedge length',
    'Storage ring B2 dipole bending radius': 'SI magnet dipole b2 hardedge bending radius',
    'Storage ring B2 dipole magnetic field': 'SI magnet dipole b2 hardedge magnetic field', 
    'Storage ring B2 dipole critical energy': 'SI magnet dipole b2 hardedge critical energy', 
    'Storage ring hardedge sagitta of B2 dipoles': 'SI magnet dipole b2 hardedge sagitta',
    'Storage ring number of B3 dipoles': 'SI magnet dipole b3 number',
    'Storage ring deflection angle of B3 dipoles': 'SI magnet dipole b3 deflection angle',
    'Storage ring hardedge length of B3 dipoles': 'SI magnet dipole b3 hardedge length',
    'Storage ring B3 dipole bending radius': 'SI magnet dipole b3 hardedge bending radius',
    'Storage ring B3 dipole magnetic field': 'SI magnet dipole b3 hardedge magnetic field',
    'Storage ring B3 dipole critical energy': 'SI magnet dipole b3 hardedge critical energy',
    'Storage ring hardedge sagitta of B3 dipoles': 'SI magnet dipole b3 hardedge sagitta',
    'Storage ring number of BC dipoles': 'SI magnet dipole bc number', 
    'Storage ring deflection angle of BC dipoles': 'SI magnet dipole bc deflection angle', 
    'Storage ring hardedge length of BC dipoles': 'SI magnet dipole bc hardedge length', 
    'Storage ring BC dipole bending radius': 'SI magnet dipole bc hardedge bending radius', 
    'Storage ring BC dipole magnetic field': 'SI magnet dipole bc hardedge magnetic field',
    'Storage ring BC dipole critical energy': 'SI magnet dipole bc hardedge critical energy',
    'Storage ring hardedge sagitta of BC dipoles': 'SI magnet dipole bc hardedge sagitta',

    'Storage ring number of beam position monitors': 'SI bpm number',   
    'Storage ring number of horizontal slow dipole correctors': 'SI magnet chs number',
    'Storage ring number of vertical slow dipole correctors': 'SI magnet cvs number',
    'Storage ring number of horizontal fast dipole correctors': 'SI magnet chf number',
    'Storage ring number of vertical fast dipole correctors': 'SI magnet cvf number',
    'Storage ring number of skew quadrupoles': 'SI magnet qs number', 
    'Storage ring horizontal slow dipole corrector maximum strength': 'SI magnet chs maximum normalized integrated field',
    'Storage ring vertical slow dipole corrector maximum strength': 'SI magnet cvs maximum normalized integrated field', 
    'Storage ring horizontal fast dipole corrector maximum strength': 'SI magnet chf maximum normalized integrated field',
    'Storage ring vertical fast dipole corrector maximum strength': 'SI magnet cvf maximum normalized integrated field',
    'Storage ring skew corrector maximum integrated strength': 'SI magnet qs maximum integrated strength',
    'Storage ring skew quadrupole maximum integrated strength': 'SI magnet qs maximum integrated strength',

    'Storage ring optics mode': 'SI optics default mode', 
    'Storage ring ---': 'SI optics tune horizontal',
    'Storage ring ---': 'SI optics tune vertical',  
    'Storage ring ---': 'SI optics tune synchrotron dipole',
    'Storage ring synchrotron tune': 'SI optics tune synchrotron', 
    'Storage ring horizontal betatron frequency': 'SI optics betatron frequency horizontal',
    'Storage ring vertical betatron frequency': 'SI optics betatron frequency vertical', 
    'Storage ring synchrotron frequency': 'SI optics synchrotron frequency', 
    
    'Storage ring natural horizontal linear chromaticity': 'SI optics natural linear chromaticity horizontal',  
    'Storage ring horizontal natural chromaticity':        'SI optics natural linear chromaticity horizontal',    
    'Storage ring natural vertical linear chromaticity': 'SI optics natural linear chromaticity vertical',
    'Storage ring vertical natural linear chromaticity': 'SI optics natural linear chromaticity vertical',
    'Storage ring vertical natural chromaticity': 'SI optics natural linear chromaticity vertical',

    'Storage ring horizontal beam size at center of long straight sections': 'SI optics beam size horizontal long straight section',
    'Storage ring horizontal beam size at center of long straight section': 'SI optics beam size horizontal long straight section',  
    'Storage ring horizontal beam size at center of short straight sections': 'SI optics beam size horizontal short straight section',
    'Storage ring horizontal beam size at center of short straight section': 'SI optics beam size horizontal short straight section',
    'Storage ring vertical beam size at center of long straight sections': 'SI optics beam size vertical long straight section',
    'Storage ring vertical beam size at center of long straight section': 'SI optics beam size vertical long straight section',  
    'Storage ring vertical beam size at center of short straight sections': 'SI optics beam size vertical short straight section',
    'Storage ring vertical beam size at center of short straight section': 'SI optics beam size vertical short straight section',
    'Storage ring horizontal beam size at center of superbend': 'SI optics beam size horizontal dipole bc',
    'Storage ring horizontal beam size at center of BC dipoles': 'SI optics beam size horizontal dipole bc',             
    'Storage ring vertical beam size at center of superbend': 'SI optics beam size vertical dipole bc',
    'Storage ring vertical beam size at center of BC dipoles': 'SI optics beam size vertical dipole bc',             

    'Storage ring horizontal beam divergence at center of long straight sections': 'SI optics beam divergence horizontal long straight section',
    'Storage ring horizontal beam divergence at center of long straight section': 'SI optics beam divergence horizontal long straight section',  
    'Storage ring horizontal beam divergence at center of short straight sections': 'SI optics beam divergence horizontal short straight section',
    'Storage ring horizontal beam divergence at center of short straight section': 'SI optics beam divergence horizontal short straight section',
    'Storage ring vertical beam divergence at center of long straight sections': 'SI optics beam divergence vertical long straight section',
    'Storage ring vertical beam divergence at center of long straight section': 'SI optics beam divergence vertical long straight section',  
    'Storage ring vertical beam divergence at center of short straight sections': 'SI optics beam divergence vertical short straight section',
    'Storage ring vertical beam divergence at center of short straight section': 'SI optics beam divergence vertical short straight section',
    'Storage ring horizontal beam divergence at center of superbend': 'SI optics beam divergence horizontal dipole bc',
    'Storage ring horizontal beam divergence at center of BC dipoles': 'SI optics beam divergence horizontal dipole bc',             
    'Storage ring vertical beam divergence at center of superbend': 'SI optics beam divergence vertical dipole bc',
    'Storage ring vertical beam divergence at center of BC dipoles': 'SI optics beam divergence vertical dipole bc', 

    'Storage ring ---': 'SI optics radiation integral i1 dipole', 
    'Storage ring ---': 'SI optics radiation integral i2 dipole', 
    'Storage ring ---': 'SI optics radiation integral i3 dipole', 
    'Storage ring ---': 'SI optics radiation integral i4 dipole', 
    'Storage ring ---': 'SI optics radiation integral i5 dipole', 
    'Storage ring ---': 'SI optics radiation integral i6 dipole', 
    'Storage ring ---': 'SI optics radiation integral i1 id',
    'Storage ring ---': 'SI optics radiation integral i2 id',
    'Storage ring ---': 'SI optics radiation integral i3 id',
    'Storage ring ---': 'SI optics radiation integral i4 id',
    'Storage ring ---': 'SI optics radiation integral i5 id',
    'Storage ring ---': 'SI optics radiation integral i6 id',
    'Storage ring ---': 'SI optics radiation integral i1',
    'Storage ring ---': 'SI optics radiation integral i2',
    'Storage ring ---': 'SI optics radiation integral i3', 
    'Storage ring ---': 'SI optics radiation integral i4', 
    'Storage ring ---': 'SI optics radiation integral i5', 
    'Storage ring ---': 'SI optics radiation integral i6', 
    'Storage ring transverse coupling': 'SI optics transverse coupling',
    'Storage ring ---': 'SI optics damping partition number vertical dipole', 
    'Storage ring ---': 'SI optics damping partition number horizontal dipole',
    'Storage ring ---': 'SI optics damping partition number longitudinal dipole',
    'Storage ring energy loss per turn from dipoles': 'SI optics energy loss per turn dipole',
    'Storage ring energy loss per turn dipoles': 'SI optics energy loss per turn dipole',
    'Storage ring radiation power from dipoles': 'SI optics radiation power dipole', 
    'Storage ring ---': 'SI optics overvoltage dipole',
    'Storage ring ---': 'SI optics synchronous phase dipole', 
    'Storage ring ---': 'SI optics linear momentum compaction dipole',
    'Storage ring ---': 'SI optics linear slip phase dipole',
    'Storage ring ---': 'SI optics rf energy acceptance dipole',
    'Storage ring ---': 'SI optics natural emittance dipole', 
    'Storage ring ---': 'SI optics natural energy spread dipole',
    'Storage ring ---': 'SI optics natural bunch length dipole',
    'Storage ring ---': 'SI optics natural bunch duration dipole', 
    'Storage ring ---': 'SI optics radiation damping time horizontal dipole',
    'Storage ring ---': 'SI optics radiation damping time vertical dipole', 
    'Storage ring ---': 'SI optics radiation damping time longitudinal dipole', 
    'Storage ring ---': 'SI optics energy loss per turn id', 
    'Storage ring ---': 'SI optics damping partition number vertical', 
    'Storage ring ---': 'SI optics damping partition number horizontal',
    'Storage ring ---': 'SI optics damping partition number longitudinal',
    'Storage ring ---': 'SI optics energy loss per turn',
    'Storage ring ---': 'SI optics radiation power', 
    'Storage ring ---': 'SI optics overvoltage',
    'Storage ring synchronous phase': 'SI optics synchronous phase', 
    'Storage ring linear momentum compaction': 'SI optics linear momentum compaction',
    'Storage ring linear slip phase': 'SI optics linear slip phase',
    'Storage ring RF energy acceptance': 'SI optics rf energy acceptance',
    'Storage ring natural emittance': 'SI optics natural emittance',
    'Storage ring natural energy spread': 'SI optics natural energy spread',
    'Storage ring natural bunch length': 'SI optics natural bunch length', 
    'Storage ring natural bunch duration': 'SI optics natural bunch duration', 
    'Storage ring horizontal radiation damping time': 'SI optics radiation damping time horizontal',
    'Storage ring vertical radiation damping time': 'SI optics radiation damping time vertical', 
    'Storage ring longitudinal radiation damping time': 'SI optics radiation damping time longitudinal', 
  

}
