function lnls_setpath_mml_at

if strcmpi(computer, 'PCWIN') || strcmpi(computer, 'PCWIN64')
    root_folder = ['C:' filesep 'Arq'];
else
    root_folder = ['/home/fac_files/code'];
end

paths = { ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'lnls' filesep 'at-mml_modified_scripts']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'mml']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'applications' filesep 'common']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'applications' filesep 'loco']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'mml' filesep 'at']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'at']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'at' filesep 'atdemos']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'at' filesep 'atgui']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'at' filesep 'atphysics']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'at' filesep 'lattice']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'at' filesep 'simulator']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'at' filesep 'simulator' filesep 'element']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'at' filesep 'simulator' filesep 'element' filesep 'obsolete']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'at' filesep 'simulator' filesep 'element' filesep 'user']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'at' filesep 'simulator' filesep 'track']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'applications' filesep 'naff' filesep 'nafflib']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'applications' filesep 'naff' filesep 'naffutils' filesep 'touscheklifetime']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'applications' filesep 'naff' filesep 'naffutils']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'applications' filesep 'naff']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'applications' filesep 'lnls']; ...
[root_folder filesep 'MatlabMiddleLayer' filesep 'Release' filesep 'lnls' filesep 'fac_scripts' filesep 'tracy3']; ...
};

for i=length(paths):-1:1
    addpath(paths{i});
end