#completion for the JobManager functions
complete -W "--description --exec --inputFiles --workingDirectory --priority --possibleHosts --help"                          pyjob_qsub.py
complete -W "--clients --showCalendar --help"                                                                                 pyjob_configs_get.py
complete -W "--clients --niceness --shutdown --MoreJobs --defnumproc --calendar --weekday --hour --minutes --num_proc --help" pyjob_configs_set.py
complete -W "--sure --help"                                                                                                   pyjob_shutdown.py
complete -W "--jobs --status --user --description --help"                                                                     pyjob_qstat.py
complete -W "--jobs --status --user --description --signal --priority --possibleHosts --queue --help"                         pyjob_qsig.py

# ---------------------------
# PATHS
# ---------------------------

# PYTHON
export PYTHONPATH=/home/fac_files/code/python/sirius_python/src:/home/fac_files/code/control/modules/CustomPlot/src:/home/fac_files/code/python/PyTasks:/home/fac_files/code/python/JobManager/src

# FAC SCRIPTS
export PATH=$PATH:/home/fac_files/code/scripts:/home/fac_files/code/python/JobManager/apps

# USERS BIN
export PATH=$PATH:~/bin/
