#!/bin/bash

maq_file=~/rodar_tracy/maquinas
maquinas=$(cat  $maq_file | grep "lnls\|sgi" | grep -v "#")
a=($( hostname ));

for maq in $maquinas; do
	echo $maq
	if [ "$maq" != "$a" ];then
		ssh $maq rm -r $1 ;
	fi
    
done
